# Copyright VMware, Inc.
# SPDX-License-Identifier: APACHE-2.0

version: '2'
services:
  jasperreports:
    image: docker.io/bitnami/jasperreports:8
    ports:
      - '8080:8080'
    volumes:
      - 'jasperreports_data:/bitnami/jasperreports'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      #- ALLOW_EMPTY_PASSWORD=yes
      - JASPERREPORTS_DATABASE_HOST=ip_address
      - JASPERREPORTS_DATABASE_PORT_NUMBER=port3306
      - JASPERREPORTS_DATABASE_USER=user
      - JASPERREPORTS_DATABASE_NAME=dbnamejasperreports
      - JASPERREPORTS_DATABASE_PASSWORD=databasepass
volumes:
  jasperreports_data:
    driver: local
